Update 2 files
- /.gitlab-ci.yml
- /test/widget_test.dart

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,15 +1,44 @@
-flutter_build_ios:
+stages:
+  - test
+  - analyse
+  - build
+
+flutter_test:
+  rules:
+  - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push"'
+  stage: test
+  script:
+    - flutter test
+  tags:
+    - flutter
+
+flutter_analyse:
+  rules:
+  - if: '$CI_COMMIT_REF_NAME != "master" && $CI_PIPELINE_SOURCE == "push"'
+  stage: analyse
+  script:
+    - metrics lib -r codeclimate  > gl-code-quality-report.json
+    - |
+      report_lines="$(wc -l gl-code-quality-report.json | cut -f1 -d" ")"
+      if [[ $report_lines -gt 10 ]]; then
+          echo "more then 10 issues found"
+          exit 1  # fail the job
+      fi
+  tags:
+    - flutter
+
+
+futter_build_android:
   stage: build
   before_script:
     - flutter packages get
     - flutter clean
   script:
-    - flutter build ios
-    - cd ios
-    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
-    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
+     - flutter build apk
   artifacts:
     paths:
-      - ios/build/Runner.ipa
+      - build/app/outputs/apk/release/app-release.apk
   tags:
     - flutter
+
+# Deploy to google drive
